openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: Get dummy/fake JSON data to use as placeholder in development or in prototype testing.
    url: https://dummyjson.com/
info:
  version: "1.0.0"
  title: Products
  description: The API for all the Products!
paths:
  /products/:
    post:
      tags:
        - Products
      requestBody:
        $ref: "#/components/requestBodies/Product"
      responses:
        200:
          description: Created
  /products/{productId}:
    get:
      tags:
        - Products
      parameters:
        - name: "productId"
          in: path
          required: true
          schema:
            type: integer
          description: the id of the product
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                products:
                  $ref: "#/components/schemas/Product"
components:
  requestBodies:
    Product:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        brand:
          type: string
          example: "Apple"
        category:
          type: string
          example: "smartphones"
        description:
          type: string
          example: "An apple mobile which is nothing like apple"
        discountPercentage:
          type: number
          example: 12.96
        images:
          type: array
          products:
            type: string
            example: "https://i.dummyjson.com/data/products/1/1.jpg"
        price:
          type: integer
          example: 549
        rating:
          type: number
          example: 4.69
        stock:
          type: integer
          example: 94
        thumbnail:
          type: string
          example: "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
        title:
          type: string
          example: "iPhone 9"
